apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgchart
  namespace: dev
  labels:
    app: orgchart
spec:
  selector:
    matchLabels:
      app: orgchart
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'dev'
        vault.hashicorp.com/auth-path: "auth/dev" 
        vault.hashicorp.com/agent-inject-secret-config: "dev/test"
        vault.hashicorp.com/log-level: "debug"
        vault.hashicorp.com/agent-inject-template-config: '{{- with secret "dev/test" -}} export test="{{ .Data.data.open_pay_merchant_id }}" {{- end }}'
      labels:
        app: orgchart
    spec:
      serviceAccountName: dev
      containers:
        - name: orgchart
          image: jweissig/app:0.0.1