on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      PATH_SERVICE:
        required: false
        type: string
    secrets:
      AWS_DEV_ACCOUNT_ID:
        required: true
      AWS_QA_ACCOUNT_ID:
        required: true
      AWS_PROD_ACCOUNT_ID:
        required: true
      AWS_PIPELINE_ACCESS_KEY_ID:
        required: true
      AWS_PIPELINE_SECRET_ACCESS_KEY:
        required: true
      PACKAGE_USERNAME:
        required: true
      PACKAGE_TOKEN:
        required: true

env:
  BUILD_SHA: ${{ github.sha }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PIPELINE_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PIPELINE_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  ROLE_DURATION_SECONDS: 2400
  AWS_DEFAULT_OUTPUT: json
  AWS_DEPLOYMENT_ROLE: pipeline
  ORGANIZATION: lineup
  SERVICE_NAME: ${{inputs.SERVICE_NAME}}
  PATH_SERVICE: ${{inputs.PATH_SERVICE}}

jobs:
  apigateway:
    name: Inject DNS and Deploy AWS
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.apigateway == 'true' }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - name: Set DEV environment variables
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "::set-env name=STAGE::dev"
          echo "::set-env name=AWS_ACCOUNT_ID::${{ secrets.AWS_DEV_ACCOUNT_ID }}"
          echo "::set-env name=DNS::https://dev.lineupapp.digital/${{ env.PATH_SERVICE }}/v3/api-docs/${{ env.SERVICE_NAME }}"
          echo "::set-env name=API_ID::$(aws apigateway get-rest-apis --query "items[?name=='$SERVICE_NAME API']" | jq -r '.[0].id')"
      - name: Set QA environment variables
        if: github.ref == 'refs/heads/qa'
        run: |
          echo "::set-env name=STAGE::qa"
          echo "::set-env name=AWS_ACCOUNT_ID::${{ secrets.AWS_QA_ACCOUNT_ID }}"
          echo "::set-env name=DNS::https://uat.lineupapp.digital/${{ env.PATH_SERVICE }}/v3/api-docs/${{ env.SERVICE_NAME }}"
          echo "::set-env name=API_ID::$(aws apigateway get-rest-apis --query "items[?name=='$SERVICE_NAME API']" | jq -r '.[0].id')"
      - name: Set PROD environment variables
        if: github.ref == 'refs/heads/prod'
        run: |
          echo "::set-env name=STAGE::prod"
          echo "::set-env name=AWS_ACCOUNT_ID::${{ secrets.AWS_PROD_ACCOUNT_ID }}"
          echo "::set-env name=DNS::https://prod.lineupapp.digital/${{ env.PATH_SERVICE }}/v3/api-docs/${{ env.SERVICE_NAME }}"
          echo "::set-env name=API_ID::$(aws apigateway get-rest-apis --query "items[?name=='$SERVICE_NAME API']" | jq -r '.[0].id')"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 🔑 Configure AWS Credentials
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/prod'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ format('arn:aws:iam::{0}:role/{1}', env.AWS_ACCOUNT_ID,env.AWS_DEPLOYMENT_ROLE) }}
          role-duration-seconds: ${{ env.ROLE_DURATION_SECONDS }}
      - name: Set DEV environment variables  to API GATEWAY
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "::set-env name=STAGE::dev"
          echo "::set-env name=API_ID::$(aws apigateway get-rest-apis --query "items[?name=='$SERVICE_NAME API']" | jq -r '.[0].id')"
      - name: Set QA environment variables to API GATEWAY
        if: github.ref == 'refs/heads/qa'
        run: |
          echo "::set-env name=STAGE::qa"
          echo "::set-env name=API_ID::$(aws apigateway get-rest-apis --query "items[?name=='$SERVICE_NAME API']" | jq -r '.[0].id')"
      - name: Set PROD environment variables to API GATEWAY
        if: github.ref == 'refs/heads/prod'
        run: |
          echo "::set-env name=STAGE::prod"
          echo "::set-env name=API_ID::$(aws apigateway get-rest-apis --query "items[?name=='$SERVICE_NAME API']" | jq -r '.[0].id')"
      - name: Download Swagger YAML
        run: |
          cd apigateway && curl -o swagger-apigateway.json ${{ env.DNS }}
      - name: Inject integration API Gateway
        run: |
          aws s3 sync s3://lineup-terraform-${{  env.STAGE  }}/apigateway  ./apigateway
          sed -i "s|PATH_SERVICE|${{ env.PATH_SERVICE }}|g" apigateway/apigateway.py
          sed -i "s|ACCOUNT_ID|${{ env.AWS_ACCOUNT_ID }}|g" apigateway/apigateway.py
          chmod +x apigateway/apigateway.py
          python apigateway/apigateway.py
          cd apigateway && base64 -i swagger_updated.json > swagger-api.json
      - name: API Gateway
        run: |
          aws apigateway put-rest-api --rest-api-id ${{  env.API_ID  }} --mode merge --no-fail-on-warnings --body file://apigateway/swagger-api.json
          sed -i "s|API_ID|${{ env.API_ID }}|g" apigateway/cors.py
          chmod +x apigateway/cors.py
          python -m pip install --upgrade pip
          pip install boto3
          python apigateway/cors.py
          aws apigateway create-deployment --rest-api-id ${{  env.API_ID  }} --stage-name ${{  env.STAGE  }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#pipeline-notifications\", \"username\": \"'${{ github.actor }}'\", \"text\": \"Workflow API-Gateway Deploy ${{ env.SERVICE_NAME }} failed! See details: '${{ github.workflow }} - https://github.com/Nilo-Innovation/${{ env.SERVICE_NAME }}/actions'.\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify Slack on Success
        if: success()
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#pipeline-notifications\", \"username\": \"'${{ github.actor }}'\", \"text\": \"Workflow API-Gateway Deploy ${{ env.SERVICE_NAME }} succeeded! See details: '${{ github.workflow }} - https://github.com/Nilo-Innovation/${{ env.SERVICE_NAME }}/actions'.\"}" ${{ secrets.SLACK_WEBHOOK_URL }}