on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      SERVICE_PORT:
        required: true
        type: string
      PATH_SERVICE:
        required: false
        type: string
    secrets:
      ALB_DEV:
        required: true
      ALB_QA:
        required: true
      ALB_PROD:
        required: true
      AWS_DEV_ACCOUNT_ID:
        required: true
      AWS_QA_ACCOUNT_ID:
        required: true
      AWS_PROD_ACCOUNT_ID:
        required: true
      AWS_PIPELINE_ACCESS_KEY_ID:
        required: true
      AWS_PIPELINE_SECRET_ACCESS_KEY:
        required: true
      PACKAGE_USERNAME:
        required: true
      PACKAGE_TOKEN:
        required: true
      NEWRELIC:
        required: true
env:
  BUILD_SHA: ${{ github.sha }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PIPELINE_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PIPELINE_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  ROLE_DURATION_SECONDS: 1200
  AWS_DEFAULT_OUTPUT: json
  AWS_DEPLOYMENT_ROLE: pipeline
  ORGANIZATION: lineup
  SERVICE_NAME: ${{inputs.SERVICE_NAME}}
  SERVICE_PORT: ${{inputs.SERVICE_PORT}}
  NEWRELIC: ${{ secrets.NEWRELIC }}

jobs:
  build:
    name: Build Docker Images
    #runs-on: [self-hosted, prod]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set DEV environment variables
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        env:
          JAVA_OPTS: "-Xmx300m -Xms250m -XX:MaxMetaspaceSize=200m -XX:MetaspaceSize=130m -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps  -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1m -Xloggc:/var/log/containers/gc-%t.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/containers"
        run: |
          echo "::set-env name=STAGE::dev"
          echo "::set-env name=DOCKER_BUILD_TARGET::debug"
          echo "::set-env name=EKS_CLUSTER_NAME::dev-lineup-k8s-cluster"
          echo "::set-env name=AWS_ACCOUNT_ID::${{ secrets.AWS_DEV_ACCOUNT_ID }}"
          echo "::set-env name=ALB::${{ secrets.ALB_DEV }}"
          echo "::set-env name=NEWRELIC::${{ secrets.NEWRELIC }}"
      - name: Set PROD environment variables
        if: github.ref == 'refs/heads/qa'
        env:
          JAVA_OPTS: "-Xmx300m -Xms250m -XX:MaxMetaspaceSize=200m -XX:MetaspaceSize=130m -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps  -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1m -Xloggc:/var/log/containers/gc-%t.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/containers"
        run: |
          echo "::set-env name=STAGE::qa"
          echo "::set-env name=DOCKER_BUILD_TARGET::debug"
          echo "::set-env name=EKS_CLUSTER_NAME::qa-lineup-k8s-cluster"
          echo "::set-env name=AWS_ACCOUNT_ID::${{ secrets.AWS_QA_ACCOUNT_ID }}"
          echo "::set-env name=ALB::${{ secrets.ALB_QA }}"
          echo "::set-env name=NEWRELIC::${{ secrets.NEWRELIC }}"
      - name: Set PROD environment variables
        if: github.ref == 'refs/heads/prod'
        env:
          JAVA_OPTS: "-Xmx300m -Xms250m -XX:MaxMetaspaceSize=200m -XX:MetaspaceSize=130m -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps  -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1m -Xloggc:/var/log/containers/gc-%t.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/containers"
        run: |
          echo "::set-env name=STAGE::prod"
          echo "::set-env name=DOCKER_BUILD_TARGET::debug"
          echo "::set-env name=EKS_CLUSTER_NAME::prod-lineup-k8s-cluster"
          echo "::set-env name=AWS_ACCOUNT_ID::${{ secrets.AWS_PROD_ACCOUNT_ID }}"
          echo "::set-env name=ALB::${{ secrets.ALB_PROD }}"
          echo "::set-env name=NEWRELIC::${{ secrets.NEWRELIC }}"
      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
      - name: 🐘 Stop Gradle Daemon(s)
        uses: eskatos/gradle-command-action@v1
        env:
          GRADLE_OPTS: -Xmx2000m -XX:MaxPermSize=256m -Dorg.gradle.jvmargs='-Xmx2048m -XX:MaxPermSize=256m'
        with:
          arguments: --stop
          gradle-version: 7.4.2
      - name: 🐘 Build Repository With Gradle
        env:
          GRADLE_OPTS: -Xmx2000m -XX:MaxPermSize=256m -Dorg.gradle.jvmargs='-Xmx2048m -XX:MaxPermSize=256m'
          GITHUB_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          echo $SERVICE_NAME
          echo 'service name ' ${{inputs.SERVICE_NAME}}
          ./gradlew $SERVICE_NAME:clean
          ./gradlew $SERVICE_NAME:build
          cd $SERVICE_NAME && curl -O https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip && unzip newrelic-java.zip
          curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && NEW_RELIC_API_KEY=NRAK-UDG50M4EH7JS925OS7KUVO5ZOHK NEW_RELIC_ACCOUNT_ID=4300341 /usr/local/bin/newrelic install -n logs-integration -y
      - uses: actions/cache/save@v3
        with: 
          path: ${{  env.SERVICE_NAME  }}/build
          key: ${{ runner.os }}-gradlew-${{  env.SERVICE_NAME  }}-${{ github.sha }}
      - name: 🔑 Configure AWS Credentials
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/prod'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ format('arn:aws:iam::{0}:role/{1}', env.AWS_ACCOUNT_ID,env.AWS_DEPLOYMENT_ROLE) }}
          role-duration-seconds: ${{ env.ROLE_DURATION_SECONDS }}
      - name: 🔓 Login to Amazon ECR
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/prod'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: 🏗️ Build, Tag, and Push Images to Amazon ECR
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/qa'
        env:
          IMAGE_TAG: latest
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DOCKER_BUILD_TARGET: ${{ env.DOCKER_BUILD_TARGET }}
          ECR_TARGET: ${{ format('{0}.dkr.ecr.us-east-1.amazonaws.com/{1}-{2}/{3}:latest',env.AWS_ACCOUNT_ID, env.STAGE, env.ORGANIZATION, env.SERVICE_NAME ) }}
        run: |
          docker buildx build --platform linux/amd64 -t $ECR_TARGET --push $SERVICE_NAME
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#pipeline-notifications\", \"username\": \"'${{ github.actor }}'\", \"text\": \"Workflow Build Spring Boot Deploy ${{ env.SERVICE_NAME }} failed! See details: '${{ github.workflow }} - https://github.com/Nilo-Innovation/${{ env.SERVICE_NAME }}/actions'.\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify Slack on Success
        if: success()
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#pipeline-notifications\", \"username\": \"'${{ github.actor }}'\", \"text\": \"Workflow Build Spring Boot Deploy ${{ env.SERVICE_NAME }} succeeded! See details: '${{ github.workflow }} - https://github.com/Nilo-Innovation/${{ env.SERVICE_NAME }}/actions'.\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
